language: ruby
rvm:
  - 1.9.3
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#holderdeord"
script: "RAILS_ENV=test bundle exec rake travis"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g buster autolint"
env:
  - DISPLAY=:99.0 COVERAGE_THRESHOLD=60
