rvm:
  - 1.9.3
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#holderdeord"
script: "bundle exec rake default"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"